name: Matrix Configuration


on:
  push:
  workflow_dispatch:


jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [busybox, nginx]
    runs-on: ${{matrix.os}}

    steps:
      - name: Echo Docker Details
        run: docker info
      - name: Run Image
        run: docker run ${{matrix.images}}


